### ISSUE TITLE
'FBX-glTF-conv' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by adamistheanswer** [cocos/FBX-glTF-conv#62]
Hey! This project could potentially be a bit of a life saver for me... but I'm having some difficulties running it, any help would me greatly apprecitated 

I've gone through the install steps with CMake and it seems to have all gone smoothly

`-- Build files have been written to: C:/Users/adam_/FBX-glTF-conv`

However when I go to run the command (I'm running it from the folder it was built to) I get the following message

`C:\Users\adam_\FBX-glTF-conv>FBX-glTF-conv "C:\Users\adam_\FBX-glTF-conv\idle.fbx" --out "C:\Users\adam_\FBX-glTF-conv"
'FBX-glTF-conv' is not recognized as an internal or external command,
operable program or batch file.`

Is there a step after the CMake install command that I'm missing? I'm a complete newbie to CMake. Am I supposed to add a path variable for FBX-glTF-conv or do I have to do something with the built files CMake generates?

I've tried this on both windows & macOS and hit the same wall

Cheers!

**Comment by shrinktofit** [comment]
If you're using Visual Studio 2019 or higher, simply open this repo by Visual Studio "open folder". 

Then open "CMake settings" in Visual Studio, type `-DFbxSdkHome=\"C:\\Program Files\\Autodesk\\FBX\\FBX SDK\\2020.0.1\"` in "CMake command line arguments".

![image](https://user-images.githubusercontent.com/28807867/157185336-23485613-4480-470a-8e1b-62541519b73e.png)

Then just generate it.
