### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by LightTemplar** [cocos/FBX-glTF-conv#69]
Could you please also make a linux release? I use Kubuntu 22.04 if it's matter.

**Comment by shrinktofit** [comment]
I'll try it.

**Comment by Chikanz** [comment]
Any updates on this?

**Comment by shrinktofit** [comment]
I run into a deployment issue when implementing this and I currently don't know how to strike it... https://github.com/shrinktofit/FBX-glTF-conv/runs/8083554602?check_suite_focus=true

**Comment by hubluesky** [comment]
Is there any progress, I use debian 11.

**Comment by LightTemplar** [comment]
@shrinktofit,
there is a later version. May be try with it? https://www.autodesk.com/developer-network/platform-technologies/fbx-sdk-2020-3

And I don't know PowerShell, but shouldn't be the line like this: `Write-Output 'yes' | $fbxSdkInstallationProgram $fbxSdkHomeLocation`?

**Comment by shrinktofit** [comment]
After some tries, I built a ubuntu release here: https://github.com/cocos/FBX-glTF-conv/releases/tag/release-v1.0.0-test.41 . But there's a pitfall, it only works on Ubuntu 22.04(or in theory later) since it was built on 22.04. Especially, Ubuntu 20.04 is not able to use.

**Comment by shrinktofit** [comment]
I'll close this PR for now.
