### ISSUE TITLE
updated to alpha.38 on m2 MacBook, still mention "bad cpu type"

### ISSUE THREAD

**Issue by iwae** [cocos/FBX-glTF-conv#72]
![](https://forum.cocos.org/uploads/default/original/3X/0/3/035d68a69beb54b3d2f3a96817ac8a1e2746fb6f.png)

**Comment by xiaozzjl** [comment]
I also encountered the same problem. My device is MacbookPro M1 Pro

**Comment by xiaozzjl** [comment]
I also encountered the same problem. My device is MacbookPro M1 Pro
![截屏2023-02-23 10 05 27](https://user-images.githubusercontent.com/5679379/220817748-e92aefff-de6e-4049-aa1a-2a14bd71977a.png)

**Comment by shrinktofit** [comment]
For those who encountered the same problem, you might need to install **Rosetta 2**:

```bash
/usr/sbin/softwareupdate --install-rosetta # or /usr/sbin/softwareupdate --install-rosetta --agree-to-license
```
