### ISSUE TITLE
Outputting a GLB file

### ISSUE THREAD

**Issue by KuroiRoy** [cocos/FBX-glTF-conv#73]
The readme suggests that it is possible to write a .glb file instead of a .gltf, .bin and folder
```      
--out arg            The output path to the .gltf or .glb file.
                     Defaults to "<working-directory>/<FBX-filename-basename>.gltf"
```

However, as far as I can tell there is no option to do so. When I give an output path with a .glb extension the utility still outputs a .gltf file, just with a different extension. 
Is it possible to export .glb files with this program?

**Comment by shrinktofit** [comment]
Resolved in #74  .

Released as https://github.com/cocos/FBX-glTF-conv/releases/tag/release-v1.0.0-alpha.39 .

Feel free to reopen this issue if this release doesn't work.
