### ISSUE TITLE
"--image-path-mode embedded" writes texture data into .glb file incorrectly

### ISSUE THREAD

**Issue by BekirConsensive** [cocos/FBX-glTF-conv#75]
Hi

I have one slight issue. As I’ve stated in the title, when I try to create a .glb file with embedded textures, it seems like the texture write operation is not correct. Model Viewer applications refuse to open such files.

I also tried to render the model in Unity, the geometry was correct but the color information from textures were unrelated.

I am using the alpha.39 version.

Thanks for this very useful tool.

**Comment by shrinktofit** [comment]
Resolved in #76   .

Released as https://github.com/cocos/FBX-glTF-conv/releases/tag/release-v1.0.0-alpha.40 .
