### ISSUE TITLE
How export glb file with embedded textures files?

### ISSUE THREAD

**Issue by YousinAsuka** [cocos/FBX-glTF-conv#81]
HI, I have a problem about glb files.How can I export a glb file with embedded teturess rather than exporting a textures folder?  
                                                          Thx!

**Comment by shrinktofit** [comment]
You can use option `--image-path-mode=embedded` and output as .glb file, for example:

```pwsh
> ./FBX-glTF-conv <path-to-fbx-file> --out=<path-to-glb-file.glb> --image-path-mode=embedded
```

**Comment by YousinAsuka** [comment]
Wwwwwwwwww~~~~Thx!!~~~~Succes with your help~~~~~
