### ISSUE TITLE
glTF Validate Error

### ISSUE THREAD

**Issue by vuphanus** [cocos/FBX-glTF-conv#87]
_When convert with this tool. It may give some errors when validate as below:_

**ERROR** 
- `GLB_CHUNK_LENGTH_UNALIGNED`: Length of chunk is not aligned to 4-byte boundaries.
- `ACCESSOR_TOTAL_OFFSET_ALIGNMENT`:  Accessor's total byteOffset isn't a multiple of componentType length 4.

**WARNING**
- `NODE_SKINNED_MESH_NON_ROOT`: Node with a skinned mesh is not root. Parent transforms will not affect a skinned mesh

**INFO**
- `UNUSED_OBJECT`: This object may be unused.

**HINT**
- `BUFFER_VIEW_TARGET_MISSING`: bufferView.target should be set for vertex or index data.

**Comment by shrinktofit** [comment]
Reproduciable FBX modle would be appreciated.

**Comment by vuphanus** [comment]
> Reproduciable FBX modle would be appreciated.

I think any FBX file will do. But here is an example:
[Ball_FBX.zip](https://github.com/cocos/FBX-glTF-conv/files/10895746/Ball_FBX.zip)
[Ball_GLB.zip](https://github.com/cocos/FBX-glTF-conv/files/10895749/Ball_GLB.zip)


By the way, I can't build from source code. 
```
- FBX-glTF-conv-master\Core\fx\include\fx/gltf.h(1879,33): warning C4996: 'nlohmann::json_abi_v3_11_2::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64 _t,double,std::allocator,nlohmann::json_abi_v3_11_2::adl_serializer,std::vector<uint8_t,std::allocator<uint8_t>>>::parse': Since 3.8.0; use parse(ptr, ptr + len)
- FBX-glTF-conv-master\Cli\ReadCliArgs.cpp(273,27): error C2039: 'OptionException': is not a member of 'cxxopts' 
- FBX-glTF-conv-master\Cli\ReadCliArgs.cpp(273,43): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int                                                                                                                    
- FBX-glTF-conv-master\Cli\ReadCliArgs.cpp(273,43): error C2143: syntax error: missing ',' before '&' 
- FBX-glTF-conv-master\Cli\ReadCliArgs.cpp(274,18): error C2065: 'ex_': undeclared identifier 
```
But this is maybe another topic
- cmake version 3.23.1
- vcpkg (2023.01.09 - 2023.02.24)
- FBX SDK 2020.3.2
- Visual Studio 2019

**Comment by vuphanus** [comment]
> Reproduciable FBX modle would be appreciated.

I think any FBX file will do. But here is an example:
[Ball_FBX.zip](https://github.com/cocos/FBX-glTF-conv/files/10895746/Ball_FBX.zip)

By the way, I can't build from source code. 
```
- FBX-glTF-conv-master\Core\fx\include\fx/gltf.h(1879,33): warning C4996: 'nlohmann::json_abi_v3_11_2::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64 _t,double,std::allocator,nlohmann::json_abi_v3_11_2::adl_serializer,std::vector<uint8_t,std::allocator<uint8_t>>>::parse': Since 3.8.0; use parse(ptr, ptr + len)
- FBX-glTF-conv-master\Cli\ReadCliArgs.cpp(273,27): error C2039: 'OptionException': is not a member of 'cxxopts' 
- FBX-glTF-conv-master\Cli\ReadCliArgs.cpp(273,43): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int                                                                                                                    
- FBX-glTF-conv-master\Cli\ReadCliArgs.cpp(273,43): error C2143: syntax error: missing ',' before '&' 
- FBX-glTF-conv-master\Cli\ReadCliArgs.cpp(274,18): error C2065: 'ex_': undeclared identifier 
```
But this is maybe another topic
- cmake version 3.23.1
- vcpkg (2023.01.09 - 2023.02.24)
- FBX SDK 2020.3.2
- Visual Studio 2019

**Comment by vuphanus** [comment]
> Reproduciable FBX modle would be appreciated.

I think any FBX file will do. More complex model file may proceed more errors and wanring. But here is an example:

- [Ball_FBX.zip](https://github.com/cocos/FBX-glTF-conv/files/10895746/Ball_FBX.zip)
- [Ball.GLB.zip](https://github.com/cocos/FBX-glTF-conv/files/10896035/Ball.GLB.zip)

**Comment by vuphanus** [comment]
> Reproduciable FBX modle would be appreciated.

I think any FBX file will do. More complex model file may proceed more errors and warning. But here is an example:

- [Ball_FBX.zip](https://github.com/cocos/FBX-glTF-conv/files/10895746/Ball_FBX.zip)
- [Ball.GLB.zip](https://github.com/cocos/FBX-glTF-conv/files/10896035/Ball.GLB.zip)

GLB file convert with _FBX-glTF-conv-1.0.0-alpha.44-win32_

**Comment by shrinktofit** [comment]
> > Reproduciable FBX modle would be appreciated.
> 
> I think any FBX file will do. More complex model file may proceed more errors and warning. But here is an example:
> 
> * [Ball_FBX.zip](https://github.com/cocos/FBX-glTF-conv/files/10895746/Ball_FBX.zip)
> * [Ball.GLB.zip](https://github.com/cocos/FBX-glTF-conv/files/10896035/Ball.GLB.zip)
> 
> GLB file convert with _FBX-glTF-conv-1.0.0-alpha.44-win32_

#94 should fix issues reported from this file, except the `NO_UNUSED_OBJECT`:

- `BUFFER_VIEW_TARGET_MISSING`
- `GLB_CHUNK_LENGTH_UNALIGNED`

**Comment by vuphanus** [comment]
@shrinktofit Thank you. Tested and files convert with this tool will be standardize format with another tools now
